[package]
name = "seda-common"
version = "0.1.0-rc1"
edition = "2021"

[features]
default = ["serde", "base64"]
cosmwasm = ["cosmwasm-schema", "cosmwasm-std"]
test-utils = []

[dependencies]
base64 = { version = "0.22.1", optional = true }
cosmwasm-schema = { version = "1.5.7", optional = true }
cosmwasm-std = { version = "1.5.7", optional = true }
cw-storage-plus = "1.2.0"
hex = "0.4.3"
lazy_static = "1.5.0"
sha3 = "0.10"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", optional = true }
thiserror = { version = "1.0" }
vrf-rs = { version = "0.0.0" }

[dev-dependencies]
schemars = { version = "0.8", features = ["semver"] }
serde_json = { version = "1.0" }
k256 = { version = "0.13" }
